version: '3.8'
services:
  erp-system-fe:
    container_name: erp-system-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - tunnel

networks:
  tunnel:
    external: true
